(import (rnrs)
		(koans about-something)
		(koans about-number)
		(koans about-list)
		(koans about-equal)
		(koans about-function)
		(koans about-let)
		(koans about-condition)
		;other koans
)

(run-about-something)
(run-about-number)
(run-about-list)
(run-about-equal)
(run-about-function)
(run-about-let)
(run-about-condition)

(display "Tests completed")
